[passwords]
Cecilia = "$2b$12$MAHRHHEwISkWV4FalrN1wO4tzgnb5xEEHOqr30Y9.apg3eS7J/u4S"
Charles = "$2b$12$EH.5qE3kfLWYf.9sbEyrwuHS6XbddJo3V7DhXN89PZZR18HHzkDf."

[cookie]
name = "causa_raiz_auth"
key = "2010@moR"
expiry_days = 1